name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  specs:
    strategy:
      matrix:
        version:
          - '34,33,32,31,30'
          - '29,28,27,26,25'
          - '24,23,22,21,19'
    name: Specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - uses: gradle/gradle-build-action@v2
      - name: Specs
        run: |
          mkdir -p birch/src/test/resources/com/gruffins/birch
          echo "birch.apiKey=apiKey" > local.properties
          echo "sdk=${{ matrix.version }}" > birch/src/test/resources/com/gruffins/birch/robolectric.properties
          ./gradlew birch:coverageReport
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
