name: Android
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  specs:
    name: Specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
      - uses: gradle/gradle-build-action@v2
      - name: Specs
        run: |
          echo "birch.apiKey=apiKey" > local.properties
          ./gradlew birch:coverageReport
      - uses: codecov/codecov-action@v3
